name: Fetch and Transform Support Data

on:
  schedule:
    - cron: "0 23 * * *"   # Daily 23:00 UTC / 07:00 SGT
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Ensure docs/archive folder exists
        run: mkdir -p docs/archive

      - name: Fetch supports.json
        run: curl -s -o docs/supports.json https://gametora.com/data/umamusume/support-cards.219b4454.json

      - name: Fetch skills.json
        run: curl -s -o docs/skills.json https://gametora.com/data/umamusume/skills.7d8a2971.json

      - name: Transform and archive JSON
        run: node docs/scripts/transform.js

      - name: Commit and push all JSON files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update supports and skills JSON with daily archive"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          branch: main
          file_pattern: |
            docs/supports.json
            docs/skills.json
            docs/transformed_supports.json
            docs/archive/*
