name: Fetch and Transform Support Data

on:
  schedule:
    - cron: "0 23 * * *"   # Daily at 23:00 UTC / 7:00 SGT
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Fetch supports.json
        run: |
          curl -s -A "Mozilla/5.0" https://gametora.com/data/umamusume/support-cards.219b4454.json -o docs/supports.json

      - name: Fetch skills.json
        run: |
          curl -s -A "Mozilla/5.0" https://gametora.com/data/umamusume/skills.7d8a2971.json -o docs/skills.json

      - name: Transform and archive JSON
        run: |
          node docs/scripts/transform.js

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update supports and skills JSON with daily archive"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          branch: main
          file_pattern: |
            docs/supports.json
            docs/skills.json
            docs/transformed_supports.json
            docs/archive/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
